# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02f24c478722c4be0b59125875292f4d396515b20afde8d8e9d08c7c854316b6fefbbadc993cffc55ecd0e1e1ab0359703e19a0ab6d77bb62796d8a0131fc3fc

test:
  secret_key_base: 22168d03206784a13ed6c5dfbb91a89eb536867a97e227b5f16d1309e4665cc67725cd6977b634b504ddb04e0896ed9f0346cf19f8b254c883630b59af81afbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
